import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import DefaultLayout from "@/components/layout";
import Footer from "@/components/footer/footer";
import HotelDining from "@/components/dining/dining";
import Offer from "@/components/offers/offers";
import Contact from "@/components/contact/contact";
import CheckOut from "@/components/check-out/checkout";
import ContactComponent from "@/components/contact/contact";
import Component from "@/components/hotel-offer/hoteloffer";
import Gallery from "@/components/gallery/gallery";
import Discount from "@/components/discount/discount";
import Discover from "@/components/discover/discover";
import Trending from "@/components/trending/trending";
import Promo from "@/components/promo/promo";
import Location from "@/components/location/location";
import Trend from "@/components/trend-activities/trend";
import AuthForm from "@/components/sign-in/sign-in";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <DefaultLayout locale={locale}>{children}</DefaultLayout>
        </NextIntlClientProvider>
        <div>
          <footer>
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}